pipeline:
  identifier: Build_pytest_example_1742866089569
  name: Build pytest-example
  orgIdentifier: default
  projectIdentifier: Mantri
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: Mantri_Github
        repoName: pytest-example
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: runlinter
                  name: run linter
                  spec:
                    shell: Sh
                    command: echo "hello"
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
